[[news]]
date = "2025-06-07"
content = "Graduated from The University of Chicago."

[[news]]
date = "2025-03-01"
content = "Will join Northwestern Kellogg as an Empirical Research Fellow."

[[news]]
date = "2024-07-01"
content = "Graduated from college."

[[news]]
date = "2024-05-15"
content = "Entering The University of Chicago MAPSS (Economics concentration) this fall."

[[news]]
date = "2024-01-01"
content = "Happy New Year!"

[[news]]
date = "2023-11-07"
content = "Presented summer research on comparative judgment reliability at the University of Birmingham."
